In [2]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.tree import DecisionTreeClassifier as DTC
from matplotlib import pyplot as plt
%matplotlib inline
import datetime
import pandas as pd
from sklearn import preprocessing as pp
from sklearn.linear_model import LogisticRegression as LR
from sklearn.neighbors import KNeighborsClassifier as KNN

import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils

Using TensorFlow backend.


In [3]:
ds = pd.read_csv('mushrooms.csv')
dat = ds.values

print dat.shape

headers = list(ds.columns.values) #store features of mushrooms
print(headers)

(8124, 23)
['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor', 'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color', 'stalk-shape', 'stalk-root', 'stalk-surface-above-ring', 'stalk-surface-below-ring', 'stalk-color-above-ring', 'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number', 'ring-type', 'spore-print-color', 'population', 'habitat']


In [12]:
#Data Preprocessing
l = pp.LabelEncoder()
l.fit(dat[:, 0])
dataa = l.transform(dat[:, 0])

#come up with appropriate numerical data set
for ix in range(1, dat.shape[1]):
    le = pp.LabelEncoder()
    le.fit(dat[:, ix])
    y = le.transform(dat[:, ix])
    dataa = np.vstack((dataa , y))
    
data = dataa.T #tranpose the metrix

cate = data[:, 0] #One hot encoding for Neural Network implementation. specify the targets.

print "data Dimenssion"
print data.shape 

print "numerically converted data set"
print dataa

print "Expected targets, converted in to metrix format"
print cate

data Dimenssion
(8124, 23)
numerically converted data set
[[1 0 0 ... 0 1 0]
 [5 5 0 ... 2 3 5]
 [2 2 2 ... 2 3 2]
 ...
 [2 3 3 ... 0 7 4]
 [3 2 2 ... 1 4 1]
 [5 1 3 ... 2 2 2]]
Expected targets, converted in to metrix format
[1 0 0 ... 0 1 0]


In [15]:
split = int(0.80 * data.shape[0])

x_train = data[:split , 1:]
y_train = data[:split, 0]

x_test = data[split: , 1:]
y_test = data[split: , 0]

print x_train.shape, y_train.shape
print x_test.shape, y_test.shape

print split

(6499, 22) (6499,)
(1625, 22) (1625,)
6499


In [5]:
y = np_utils.to_categorical(cate)
Y_train = y[:split]
Y_test = y[split:]

print x_train.shape, x_test.shape
print y_train.shape, y_test.shape
print data.shape

(6499, 22) (1625, 22)
(6499,) (1625,)
(8124, 23)


In [6]:
#use sequential type to create the model. All the layer are 
#dense layers which means all the neurons are connected together
model = Sequential()

model.add(Dense(11, input_shape=(22,)))
model.add(Activation('relu'))

model.add(Dense(5))
model.add(Activation('relu'))

model.add(Dense(2))
model.add(Activation('softmax'))

model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 11)                253       
_________________________________________________________________
activation_1 (Activation)    (None, 11)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 60        
_________________________________________________________________
activation_2 (Activation)    (None, 5)                 0         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 12        
_________________________________________________________________
activation_3 (Activation)    (None, 2)                 0         
Total params: 325
Trainable params: 325
Non-trainable params: 0
______

In [7]:
hist = model.fit(x_train, Y_train,
         nb_epoch=1000,
         shuffle=True,
         batch_size=128,
         validation_data=(x_test, Y_test))

Instructions for updating:
Use tf.cast instead.


/Users/sachi/anaconda3/envs/research/lib/python2.7/site-packages/ipykernel_launcher.py:5: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """


Train on 6499 samples, validate on 1625 samples
Epoch 1/1000
6499/6499 [==============================] - 2s 287us/step - loss: 0.7142 - acc: 0.5541 - val_loss: 0.7467 - val_acc: 0.3120
Epoch 2/1000
6499/6499 [==============================] - 0s 28us/step - loss: 0.6267 - acc: 0.6284 - val_loss: 0.7378 - val_acc: 0.3120
Epoch 3/1000
6499/6499 [==============================] - 0s 28us/step - loss: 0.5728 - acc: 0.6980 - val_loss: 0.6747 - val_acc: 0.3858
Epoch 4/1000
6499/6499 [==============================] - 0s 32us/step - loss: 0.5215 - acc: 0.7561 - val_loss: 0.6078 - val_acc: 0.5729
Epoch 5/1000
6499/6499 [==============================] - 0s 30us/step - loss: 0.4771 - acc: 0.7906 - val_loss: 0.5598 - val_acc: 0.8271
Epoch 6/1000
6499/6499 [==============================] - 0s 28us/step - loss: 0.4312 - acc: 0.8258 - val_loss: 0.5369 - val_acc: 0.8855
Epoch 7/1000
6499/6499 [==============================] - 0s 27us/step - loss: 0.3857 - acc: 0.8504 - val_loss: 0.4568 - val_acc:

6499/6499 [==============================] - 0s 30us/step - loss: 0.0130 - acc: 0.9995 - val_loss: 0.2656 - val_acc: 0.9268
Epoch 61/1000
6499/6499 [==============================] - 0s 32us/step - loss: 0.0123 - acc: 0.9997 - val_loss: 0.2584 - val_acc: 0.9262
Epoch 62/1000
6499/6499 [==============================] - 0s 30us/step - loss: 0.0118 - acc: 0.9997 - val_loss: 0.2385 - val_acc: 0.9434
Epoch 63/1000
6499/6499 [==============================] - 0s 31us/step - loss: 0.0113 - acc: 0.9998 - val_loss: 0.2370 - val_acc: 0.9403
Epoch 64/1000
6499/6499 [==============================] - 0s 29us/step - loss: 0.0108 - acc: 0.9997 - val_loss: 0.2254 - val_acc: 0.9434
Epoch 65/1000
6499/6499 [==============================] - 0s 31us/step - loss: 0.0103 - acc: 0.9998 - val_loss: 0.2341 - val_acc: 0.9403
Epoch 66/1000
6499/6499 [==============================] - 0s 31us/step - loss: 0.0100 - acc: 0.9998 - val_loss: 0.2253 - val_acc: 0.9477
Epoch 67/1000
6499/6499 [=======================

Epoch 119/1000
6499/6499 [==============================] - 0s 31us/step - loss: 0.0015 - acc: 1.0000 - val_loss: 0.1622 - val_acc: 0.9742
Epoch 120/1000
6499/6499 [==============================] - 0s 31us/step - loss: 0.0015 - acc: 1.0000 - val_loss: 0.1627 - val_acc: 0.9748
Epoch 121/1000
6499/6499 [==============================] - 0s 32us/step - loss: 0.0014 - acc: 1.0000 - val_loss: 0.1630 - val_acc: 0.9748
Epoch 122/1000
6499/6499 [==============================] - 0s 30us/step - loss: 0.0014 - acc: 1.0000 - val_loss: 0.1613 - val_acc: 0.9748
Epoch 123/1000
6499/6499 [==============================] - 0s 30us/step - loss: 0.0014 - acc: 1.0000 - val_loss: 0.1594 - val_acc: 0.9742
Epoch 124/1000
6499/6499 [==============================] - 0s 32us/step - loss: 0.0013 - acc: 1.0000 - val_loss: 0.1637 - val_acc: 0.9754
Epoch 125/1000
6499/6499 [==============================] - 0s 31us/step - loss: 0.0013 - acc: 1.0000 - val_loss: 0.1633 - val_acc: 0.9754
Epoch 126/1000
6499/6499 [=

6499/6499 [==============================] - 0s 28us/step - loss: 3.2006e-04 - acc: 1.0000 - val_loss: 0.1598 - val_acc: 0.9766
Epoch 177/1000
6499/6499 [==============================] - 0s 26us/step - loss: 3.1194e-04 - acc: 1.0000 - val_loss: 0.1610 - val_acc: 0.9766
Epoch 178/1000
6499/6499 [==============================] - 0s 26us/step - loss: 3.0371e-04 - acc: 1.0000 - val_loss: 0.1613 - val_acc: 0.9766
Epoch 179/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.9556e-04 - acc: 1.0000 - val_loss: 0.1638 - val_acc: 0.9766
Epoch 180/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.9090e-04 - acc: 1.0000 - val_loss: 0.1629 - val_acc: 0.9766
Epoch 181/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.8162e-04 - acc: 1.0000 - val_loss: 0.1602 - val_acc: 0.9766
Epoch 182/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.7371e-04 - acc: 1.0000 - val_loss: 0.1602 - val_acc: 0.9766
Epoch 183/1000

6499/6499 [==============================] - 0s 28us/step - loss: 7.7354e-05 - acc: 1.0000 - val_loss: 0.1650 - val_acc: 0.9785
Epoch 234/1000
6499/6499 [==============================] - 0s 26us/step - loss: 7.5303e-05 - acc: 1.0000 - val_loss: 0.1643 - val_acc: 0.9785
Epoch 235/1000
6499/6499 [==============================] - 0s 26us/step - loss: 7.3513e-05 - acc: 1.0000 - val_loss: 0.1647 - val_acc: 0.9785
Epoch 236/1000
6499/6499 [==============================] - 0s 26us/step - loss: 7.2118e-05 - acc: 1.0000 - val_loss: 0.1659 - val_acc: 0.9778
Epoch 237/1000
6499/6499 [==============================] - 0s 26us/step - loss: 7.0046e-05 - acc: 1.0000 - val_loss: 0.1652 - val_acc: 0.9785
Epoch 238/1000
6499/6499 [==============================] - 0s 28us/step - loss: 6.8263e-05 - acc: 1.0000 - val_loss: 0.1663 - val_acc: 0.9785
Epoch 239/1000
6499/6499 [==============================] - 0s 26us/step - loss: 6.6822e-05 - acc: 1.0000 - val_loss: 0.1684 - val_acc: 0.9772
Epoch 240/1000

6499/6499 [==============================] - 0s 32us/step - loss: 1.9544e-05 - acc: 1.0000 - val_loss: 0.1693 - val_acc: 0.9791
Epoch 291/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.9013e-05 - acc: 1.0000 - val_loss: 0.1710 - val_acc: 0.9791
Epoch 292/1000
6499/6499 [==============================] - 0s 30us/step - loss: 1.8556e-05 - acc: 1.0000 - val_loss: 0.1672 - val_acc: 0.9791
Epoch 293/1000
6499/6499 [==============================] - 0s 32us/step - loss: 1.8103e-05 - acc: 1.0000 - val_loss: 0.1675 - val_acc: 0.9791
Epoch 294/1000
6499/6499 [==============================] - 0s 31us/step - loss: 1.7665e-05 - acc: 1.0000 - val_loss: 0.1685 - val_acc: 0.9791
Epoch 295/1000
6499/6499 [==============================] - 0s 31us/step - loss: 1.7273e-05 - acc: 1.0000 - val_loss: 0.1689 - val_acc: 0.9791
Epoch 296/1000
6499/6499 [==============================] - 0s 28us/step - loss: 1.6895e-05 - acc: 1.0000 - val_loss: 0.1691 - val_acc: 0.9791
Epoch 297/1000

6499/6499 [==============================] - 0s 28us/step - loss: 5.0422e-06 - acc: 1.0000 - val_loss: 0.1719 - val_acc: 0.9791
Epoch 348/1000
6499/6499 [==============================] - 0s 27us/step - loss: 4.9501e-06 - acc: 1.0000 - val_loss: 0.1769 - val_acc: 0.9791
Epoch 349/1000
6499/6499 [==============================] - 0s 33us/step - loss: 4.8234e-06 - acc: 1.0000 - val_loss: 0.1703 - val_acc: 0.9791
Epoch 350/1000
6499/6499 [==============================] - 0s 31us/step - loss: 4.7018e-06 - acc: 1.0000 - val_loss: 0.1716 - val_acc: 0.9791
Epoch 351/1000
6499/6499 [==============================] - 0s 30us/step - loss: 4.6091e-06 - acc: 1.0000 - val_loss: 0.1724 - val_acc: 0.9791
Epoch 352/1000
6499/6499 [==============================] - 0s 31us/step - loss: 4.5267e-06 - acc: 1.0000 - val_loss: 0.1663 - val_acc: 0.9797
Epoch 353/1000
6499/6499 [==============================] - 0s 28us/step - loss: 4.3959e-06 - acc: 1.0000 - val_loss: 0.1747 - val_acc: 0.9791
Epoch 354/1000

6499/6499 [==============================] - 0s 37us/step - loss: 1.3890e-06 - acc: 1.0000 - val_loss: 0.1701 - val_acc: 0.9803
Epoch 405/1000
6499/6499 [==============================] - 0s 35us/step - loss: 1.3641e-06 - acc: 1.0000 - val_loss: 0.1682 - val_acc: 0.9815
Epoch 406/1000
6499/6499 [==============================] - 0s 38us/step - loss: 1.3282e-06 - acc: 1.0000 - val_loss: 0.1690 - val_acc: 0.9815
Epoch 407/1000
6499/6499 [==============================] - 0s 31us/step - loss: 1.3074e-06 - acc: 1.0000 - val_loss: 0.1719 - val_acc: 0.9797
Epoch 408/1000
6499/6499 [==============================] - 0s 31us/step - loss: 1.2722e-06 - acc: 1.0000 - val_loss: 0.1718 - val_acc: 0.9803
Epoch 409/1000
6499/6499 [==============================] - 0s 30us/step - loss: 1.2482e-06 - acc: 1.0000 - val_loss: 0.1733 - val_acc: 0.9797
Epoch 410/1000
6499/6499 [==============================] - 0s 32us/step - loss: 1.2176e-06 - acc: 1.0000 - val_loss: 0.1703 - val_acc: 0.9815
Epoch 411/1000

6499/6499 [==============================] - 0s 33us/step - loss: 4.5177e-07 - acc: 1.0000 - val_loss: 0.1667 - val_acc: 0.9834
Epoch 462/1000
6499/6499 [==============================] - 0s 31us/step - loss: 4.4375e-07 - acc: 1.0000 - val_loss: 0.1728 - val_acc: 0.9815
Epoch 463/1000
6499/6499 [==============================] - 0s 32us/step - loss: 4.3649e-07 - acc: 1.0000 - val_loss: 0.1689 - val_acc: 0.9834
Epoch 464/1000
6499/6499 [==============================] - 0s 30us/step - loss: 4.2913e-07 - acc: 1.0000 - val_loss: 0.1695 - val_acc: 0.9834
Epoch 465/1000
6499/6499 [==============================] - 0s 29us/step - loss: 4.2205e-07 - acc: 1.0000 - val_loss: 0.1704 - val_acc: 0.9828
Epoch 466/1000
6499/6499 [==============================] - 0s 32us/step - loss: 4.1510e-07 - acc: 1.0000 - val_loss: 0.1708 - val_acc: 0.9815
Epoch 467/1000
6499/6499 [==============================] - 0s 31us/step - loss: 4.0939e-07 - acc: 1.0000 - val_loss: 0.1710 - val_acc: 0.9822
Epoch 468/1000

6499/6499 [==============================] - 0s 28us/step - loss: 2.1168e-07 - acc: 1.0000 - val_loss: 0.1670 - val_acc: 0.9834
Epoch 519/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.0957e-07 - acc: 1.0000 - val_loss: 0.1659 - val_acc: 0.9840
Epoch 520/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.0741e-07 - acc: 1.0000 - val_loss: 0.1654 - val_acc: 0.9834
Epoch 521/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.0556e-07 - acc: 1.0000 - val_loss: 0.1638 - val_acc: 0.9840
Epoch 522/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.0418e-07 - acc: 1.0000 - val_loss: 0.1648 - val_acc: 0.9834
Epoch 523/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.0208e-07 - acc: 1.0000 - val_loss: 0.1675 - val_acc: 0.9834
Epoch 524/1000
6499/6499 [==============================] - 0s 26us/step - loss: 2.0025e-07 - acc: 1.0000 - val_loss: 0.1643 - val_acc: 0.9840
Epoch 525/1000

6499/6499 [==============================] - 0s 27us/step - loss: 1.4852e-07 - acc: 1.0000 - val_loss: 0.1647 - val_acc: 0.9834
Epoch 576/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.4855e-07 - acc: 1.0000 - val_loss: 0.1645 - val_acc: 0.9834
Epoch 577/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.4808e-07 - acc: 1.0000 - val_loss: 0.1632 - val_acc: 0.9840
Epoch 578/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.4715e-07 - acc: 1.0000 - val_loss: 0.1662 - val_acc: 0.9834
Epoch 579/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.4584e-07 - acc: 1.0000 - val_loss: 0.1645 - val_acc: 0.9840
Epoch 580/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.4582e-07 - acc: 1.0000 - val_loss: 0.1650 - val_acc: 0.9834
Epoch 581/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.4582e-07 - acc: 1.0000 - val_loss: 0.1656 - val_acc: 0.9834
Epoch 582/1000

6499/6499 [==============================] - 0s 28us/step - loss: 1.3087e-07 - acc: 1.0000 - val_loss: 0.1623 - val_acc: 0.9840
Epoch 633/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.2985e-07 - acc: 1.0000 - val_loss: 0.1640 - val_acc: 0.9840
Epoch 634/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.2986e-07 - acc: 1.0000 - val_loss: 0.1625 - val_acc: 0.9840
Epoch 635/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.2985e-07 - acc: 1.0000 - val_loss: 0.1646 - val_acc: 0.9840
Epoch 636/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.2985e-07 - acc: 1.0000 - val_loss: 0.1635 - val_acc: 0.9840
Epoch 637/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.2985e-07 - acc: 1.0000 - val_loss: 0.1644 - val_acc: 0.9840
Epoch 638/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.2985e-07 - acc: 1.0000 - val_loss: 0.1626 - val_acc: 0.9840
Epoch 639/1000

6499/6499 [==============================] - 0s 31us/step - loss: 1.2453e-07 - acc: 1.0000 - val_loss: 0.1625 - val_acc: 0.9840
Epoch 690/1000
6499/6499 [==============================] - 0s 37us/step - loss: 1.2453e-07 - acc: 1.0000 - val_loss: 0.1649 - val_acc: 0.9834
Epoch 691/1000
6499/6499 [==============================] - 0s 33us/step - loss: 1.2453e-07 - acc: 1.0000 - val_loss: 0.1626 - val_acc: 0.9840
Epoch 692/1000
6499/6499 [==============================] - 0s 31us/step - loss: 1.2453e-07 - acc: 1.0000 - val_loss: 0.1625 - val_acc: 0.9840
Epoch 693/1000
6499/6499 [==============================] - 0s 28us/step - loss: 1.2453e-07 - acc: 1.0000 - val_loss: 0.1625 - val_acc: 0.9840
Epoch 694/1000
6499/6499 [==============================] - 0s 40us/step - loss: 1.2453e-07 - acc: 1.0000 - val_loss: 0.1625 - val_acc: 0.9840
Epoch 695/1000
6499/6499 [==============================] - 0s 32us/step - loss: 1.2453e-07 - acc: 1.0000 - val_loss: 0.1626 - val_acc: 0.9840
Epoch 696/1000

6499/6499 [==============================] - 0s 30us/step - loss: 1.2187e-07 - acc: 1.0000 - val_loss: 0.1623 - val_acc: 0.9840
Epoch 747/1000
6499/6499 [==============================] - 0s 32us/step - loss: 1.2187e-07 - acc: 1.0000 - val_loss: 0.1604 - val_acc: 0.9840
Epoch 748/1000
6499/6499 [==============================] - 0s 30us/step - loss: 1.2187e-07 - acc: 1.0000 - val_loss: 0.1623 - val_acc: 0.9840
Epoch 749/1000
6499/6499 [==============================] - 0s 30us/step - loss: 1.2187e-07 - acc: 1.0000 - val_loss: 0.1624 - val_acc: 0.9840
Epoch 750/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.2187e-07 - acc: 1.0000 - val_loss: 0.1624 - val_acc: 0.9840
Epoch 751/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.2187e-07 - acc: 1.0000 - val_loss: 0.1631 - val_acc: 0.9840
Epoch 752/1000
6499/6499 [==============================] - 0s 31us/step - loss: 1.2187e-07 - acc: 1.0000 - val_loss: 0.1620 - val_acc: 0.9840
Epoch 753/1000

6499/6499 [==============================] - 0s 29us/step - loss: 1.2056e-07 - acc: 1.0000 - val_loss: 0.1609 - val_acc: 0.9840
Epoch 804/1000
6499/6499 [==============================] - 0s 32us/step - loss: 1.2054e-07 - acc: 1.0000 - val_loss: 0.1627 - val_acc: 0.9840
Epoch 805/1000
6499/6499 [==============================] - 0s 33us/step - loss: 1.2054e-07 - acc: 1.0000 - val_loss: 0.1627 - val_acc: 0.9840
Epoch 806/1000
6499/6499 [==============================] - 0s 36us/step - loss: 1.2054e-07 - acc: 1.0000 - val_loss: 0.1627 - val_acc: 0.9840
Epoch 807/1000
6499/6499 [==============================] - 0s 34us/step - loss: 1.2054e-07 - acc: 1.0000 - val_loss: 0.1628 - val_acc: 0.9840
Epoch 808/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.2054e-07 - acc: 1.0000 - val_loss: 0.1618 - val_acc: 0.9840
Epoch 809/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.2054e-07 - acc: 1.0000 - val_loss: 0.1618 - val_acc: 0.9840
Epoch 810/1000

6499/6499 [==============================] - 0s 30us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1598 - val_acc: 0.9840
Epoch 861/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 862/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 863/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 864/1000
6499/6499 [==============================] - 0s 27us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 865/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 866/1000
6499/6499 [==============================] - 0s 28us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1601 - val_acc: 0.9840
Epoch 867/1000

6499/6499 [==============================] - 0s 26us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1623 - val_acc: 0.9840
Epoch 918/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 919/1000
6499/6499 [==============================] - 0s 25us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1603 - val_acc: 0.9840
Epoch 920/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1603 - val_acc: 0.9840
Epoch 921/1000
6499/6499 [==============================] - 0s 25us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1604 - val_acc: 0.9840
Epoch 922/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1604 - val_acc: 0.9840
Epoch 923/1000
6499/6499 [==============================] - 0s 25us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1604 - val_acc: 0.9840
Epoch 924/1000

6499/6499 [==============================] - 0s 35us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 975/1000
6499/6499 [==============================] - 0s 37us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 976/1000
6499/6499 [==============================] - 0s 38us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 977/1000
6499/6499 [==============================] - 0s 29us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 978/1000
6499/6499 [==============================] - 0s 26us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1597 - val_acc: 0.9840
Epoch 979/1000
6499/6499 [==============================] - 0s 32us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1598 - val_acc: 0.9840
Epoch 980/1000
6499/6499 [==============================] - 0s 31us/step - loss: 1.1921e-07 - acc: 1.0000 - val_loss: 0.1598 - val_acc: 0.9840
Epoch 981/1000

In [ ]:
plt.figure(figsize=(14,3))
plt.subplot(1, 2, 1)
plt.suptitle('Optimizer : Adam', fontsize=10)
plt.ylabel('Loss', fontsize=16)
plt.plot(hist.history['loss'], 'b', label='Training Loss')
plt.plot(hist.history['val_loss'], 'r', label='Validation Loss')
plt.legend(loc='upper right')

plt.subplot(1, 2, 2)
plt.ylabel('Accuracy', fontsize=16)
plt.plot(hist.history['acc'], 'b', label='Training Accuracy')
plt.plot(hist.history['val_acc'], 'r', label='Validation Accuracy')
plt.legend(loc='lower right')
plt.show()